# Generated by Django 3.0.3 on 2020-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_case', models.CharField(max_length=20)),
                ('rules', models.TextField()),
                ('matter_type', models.CharField(max_length=10)),
                ('bench_type', models.CharField(max_length=20)),
                ('case_type', models.CharField(max_length=50)),
                ('connected_case', models.BooleanField()),
                ('connected_case_type', models.CharField(blank=True, max_length=20)),
                ('connected_case_number', models.IntegerField(blank=True)),
                ('connected_case_year', models.IntegerField(blank=True)),
                ('filing_urgency', models.BooleanField()),
                ('filing_status', models.IntegerField(default=3)),
                ('checklist_8', models.BooleanField(default=True)),
                ('checklist_9', models.BooleanField(default=True)),
                ('checklist_10', models.BooleanField(default=True)),
                ('checklist_11', models.BooleanField(default=True)),
                ('checklist_15', models.BooleanField(default=True)),
                ('checklist_16', models.BooleanField(default=True)),
                ('checklist_17', models.BooleanField(default=True)),
                ('checklist_21', models.BooleanField(default=True)),
                ('checklist_25', models.BooleanField(default=True)),
                ('checklist_31', models.BooleanField(default=True)),
                ('filing_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.IntegerField(default=3)),
                ('response_comments', models.TextField(blank=True)),
            ],
        ),
    ]
