# Generated by Django 3.0.3 on 2020-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0002_auto_20200513_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='filing_case',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
