# Generated by Django 3.0.3 on 2020-05-14 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0003_auto_20200513_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='respond_to_case',
            new_name='respond_to_case_id',
        ),
        migrations.AddField(
            model_name='filing',
            name='filing_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='filing',
            name='connected_case_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='filing',
            name='connected_case_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='filing',
            name='connected_case_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
