# Generated by Django 3.0.3 on 2020-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0005_auto_20200514_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='advocate_hc_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='filing',
            name='filing_comments',
            field=models.TextField(blank=True, default='Pending Review'),
        ),
    ]
