# Generated by Django 3.0.3 on 2020-05-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0006_auto_20200514_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='LoEventsFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='annexFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='indexFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='memoFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='othFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='pastFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='synopsisFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='urgencyFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='vnamFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
    ]
