# Generated by Django 3.0.3 on 2020-05-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0007_auto_20200515_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filing',
            name='LoEventsFile',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='annexFile',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='indexFile',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='memoFile',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='othFile',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='pastFile',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='synopsisFile',
        ),
        migrations.RemoveField(
            model_name='filing',
            name='vnamFile',
        ),
    ]
