# Generated by Django 3.0.3 on 2020-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0008_auto_20200515_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='LoEventsFile',
            field=models.FileField(default='', upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='annexFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='indexFile',
            field=models.FileField(default='', upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='memoFile',
            field=models.FileField(default='', upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='othFile',
            field=models.FileField(blank=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='pastFile',
            field=models.FileField(default='', upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='synopsisFile',
            field=models.FileField(default='', upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filing',
            name='vnamFile',
            field=models.FileField(default='', upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='advocate_hc_code',
            field=models.CharField(max_length=10),
        ),
    ]
