# Generated by Django 3.0.3 on 2020-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0009_auto_20200515_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='officer_stamp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='response',
            name='officer_stamp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='response',
            name='response_note',
            field=models.TextField(blank=True),
        ),
    ]
