# Generated by Django 3.0.3 on 2020-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0012_auto_20200516_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='LoEventsFile',
            field=models.FileField(upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='annexFile',
            field=models.FileField(blank=True, null=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='indexFile',
            field=models.FileField(upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='memoFile',
            field=models.FileField(upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='othFile',
            field=models.FileField(blank=True, null=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='pastFile',
            field=models.FileField(upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='synopsisFile',
            field=models.FileField(upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='urgencyFile',
            field=models.FileField(blank=True, null=True, upload_to='filings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='vnamFile',
            field=models.FileField(upload_to='filings/%Y/%m/%d/'),
        ),
    ]
