# Generated by Django 3.0.3 on 2020-05-16 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0014_auto_20200516_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
