# Generated by Django 3.0.3 on 2020-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0015_response_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_comments',
            field=models.TextField(blank=True, default='Pending Review'),
        ),
    ]
