# Generated by Django 3.0.3 on 2020-05-22 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0018_auto_20200521_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='sanat_number',
            field=models.CharField(default=1212, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='sanat_number',
            field=models.CharField(default=1212, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='affidavit_in_response',
            field=models.FileField(blank=True, null=True, upload_to='filings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='further_affidavit',
            field=models.FileField(blank=True, null=True, upload_to='filings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='othFile',
            field=models.FileField(blank=True, null=True, upload_to='filings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='vnamFile',
            field=models.FileField(default='', upload_to='filings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
