# Generated by Django 3.0.3 on 2020-05-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_auto_20200515_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
